version: "3"
services:
  service-a:
      build:
        context: ./service_a
        dockerfile: Dockerfile
      ports:
        - "8081:8080"
  service-b:
      build:
        context: ./service_b
        dockerfile: Dockerfile
      ports:
        - "8082:8080"

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"